version: '3.7'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5001 manage:app --timeout 600
    expose:
      - 5001
    env_file:
      - ./.env.prod
  kaldi-serve:
    build: ./services/kaldi-serve
    command: /home/app/kaldi-serve-init
    expose:
      - 5002
    env_file:
      - ./.env.prod
  finnish-forced-align:
    build: ./services/finnish-forced-align
    command: /home/app/finnish-forced-align-init
    expose:
      - 5003
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
  redis:
    build: ./services/redis
    expose:
      - 6379
    # links:
    #   - web
    # depends_on:
    #   - web
#      - kaldi-serve
